project:
  type: website

website:
  title: "Haniah Kring"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
        - href: silmarillion-characters.qmd
          text: Visualizing Book Characters
        - href: erie.qmd
          text: Lake Erie Analysis
        - href: tableclothr.qmd
          text: tableclothr
      - href: resume/kring-resume.html
        text: Resume
  page-footer:
    center: |
      [Contact Me](mailto:hrishonkring@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org/)
    right: |
      [Github Code Repo](https://github.com/hrkring/hrkring.github.io)
    background: "#404040"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
