project:
  type: website

website:
  title: "The Repository"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
        - href: erie.qmd
          text: Lake Erie Analysis
        - text: gtthemes
      - href: resume/kring-resume.html
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
